#!/usr/bin/env bash
#
# SPARK_OS Executive Orchestrator Loop
#
# Picks up task files from 02-Tasks/Pending/, routes each through CEO_Agent
# for triage/delegation to the appropriate executive or tactical agent,
# and (once the assigned agent — human or Claude Code — has executed the
# task) moves completed files to 02-Tasks/Completed/ and appends a summary
# to today's daily briefing.
#
# This script is a scaffolding/coordination layer, not a replacement for
# an agent's judgment. It does not itself write code or make business
# decisions — it surfaces work for CEO_Agent (and Claude Code, when run
# via `claude`) to act on, and keeps the task pipeline moving.
#
# Usage:
#   ./run-autonomous-loop.sh              run one pass over Pending/
#   ./run-autonomous-loop.sh --watch       re-run every INTERVAL_SECONDS
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPARK_OS_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

PENDING_DIR="${SPARK_OS_DIR}/02-Tasks/Pending"
APPROVAL_DIR="${SPARK_OS_DIR}/02-Tasks/Needs_Approval"
COMPLETED_DIR="${SPARK_OS_DIR}/02-Tasks/Completed"
BRIEFINGS_DIR="${SPARK_OS_DIR}/05-Daily-Briefings"
CEO_AGENT="${SPARK_OS_DIR}/03-Agents/CEO_Agent.md"

INTERVAL_SECONDS="${INTERVAL_SECONDS:-1800}"
TODAY="$(date +%F)"
BRIEFING_FILE="${BRIEFINGS_DIR}/${TODAY}.md"

log() {
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

ensure_briefing_exists() {
  if [ ! -f "${BRIEFING_FILE}" ]; then
    cat > "${BRIEFING_FILE}" <<EOF
# Daily Briefing — ${TODAY}

## Summary

_Auto-generated by run-autonomous-loop.sh. CEO_Agent should review and refine this narrative._

## Shipped

## Pending

## Needs Approval

## Blocked

## Notes for Tomorrow

EOF
    log "Created new daily briefing: ${BRIEFING_FILE}"
  fi
}

append_briefing_line() {
  local section="$1"
  local line="$2"
  # Insert the line under the given section header, appended after any
  # existing content in that section (simple append-before-next-header).
  awk -v section="## ${section}" -v newline="- ${line}" '
    BEGIN { inserted = 0; in_section = 0 }
    {
      if ($0 == section) {
        print
        in_section = 1
        next
      }
      if (in_section && $0 ~ /^## /) {
        print newline
        print ""
        inserted = 1
        in_section = 0
      }
      print
    }
    END {
      if (in_section && !inserted) {
        print newline
      }
    }
  ' "${BRIEFING_FILE}" > "${BRIEFING_FILE}.tmp" && mv "${BRIEFING_FILE}.tmp" "${BRIEFING_FILE}"
}

route_task() {
  local task_file="$1"
  local task_name
  task_name="$(basename "${task_file}")"

  log "Routing task '${task_name}' through CEO_Agent (${CEO_AGENT})"

  # Extract the owning agent from a line like "**Agent:** CMO_Agent" or
  # "Assigned: CTO_Agent" in the task file, if present. Falls back to
  # "Unassigned" so CEO_Agent can triage manually.
  local owner
  owner="$(grep -Eom1 '[A-Za-z]+_Agent' "${task_file}" || echo "Unassigned")"

  log "Task '${task_name}' owner: ${owner}"

  # NOTE: Actual execution (code changes, copy drafts, financial updates,
  # etc.) is performed by the assigned agent via Claude Code, not by this
  # shell script. This loop's job is routing, bookkeeping, and reporting.
  # Requires human-in-the-loop or `claude` CLI invocation to execute the
  # task content itself.

  if grep -qi 'needs approval\|requires approval\|NEEDS_APPROVAL' "${task_file}"; then
    log "Task '${task_name}' requires approval — moving to Needs_Approval/"
    mv "${task_file}" "${APPROVAL_DIR}/${task_name}"
    append_briefing_line "Needs Approval" "${task_name} (owner: ${owner})"
    return
  fi

  append_briefing_line "Pending" "${task_name} (owner: ${owner}) — routed, awaiting execution"
}

complete_task() {
  local task_file="$1"
  local task_name
  task_name="$(basename "${task_file}")"
  local timestamp
  timestamp="$(date '+%Y-%m-%d %H:%M:%S')"

  echo "" >> "${task_file}"
  echo "---" >> "${task_file}"
  echo "**Completed:** ${timestamp}" >> "${task_file}"

  mv "${task_file}" "${COMPLETED_DIR}/${task_name}"
  append_briefing_line "Shipped" "${task_name} — completed ${timestamp}"
  log "Moved '${task_name}' to Completed/"
}

run_pass() {
  ensure_briefing_exists

  shopt -s nullglob
  local tasks=("${PENDING_DIR}"/*.md)
  shopt -u nullglob

  if [ ${#tasks[@]} -eq 0 ]; then
    log "No pending tasks in ${PENDING_DIR}"
    return
  fi

  for task_file in "${tasks[@]}"; do
    route_task "${task_file}"
  done

  log "Pass complete. ${#tasks[@]} task(s) routed. Execute assigned work via Claude Code, then call:"
  log "  complete_task \"<path-to-task-in-Pending-or-Needs_Approval>\""
}

main() {
  mkdir -p "${PENDING_DIR}" "${APPROVAL_DIR}" "${COMPLETED_DIR}" "${BRIEFINGS_DIR}"

  if [ "${1:-}" = "--watch" ]; then
    log "Starting watch loop (interval: ${INTERVAL_SECONDS}s). Ctrl+C to stop."
    while true; do
      run_pass
      sleep "${INTERVAL_SECONDS}"
    done
  else
    run_pass
  fi
}

main "$@"
